services:
  tmodloader:
    image: hexlo/terraria-tmodloader-server:latest
    container_name: tmodloader
    ports:
      - "7777:7777/tcp"
    volumes:
      - ./tmod_data:/root/.local/share/Terraria
    environment:
      - WORLD_NAME="Los homosapiens"
      - WORLD_SIZE=3
      - WORLD_DIFFICULTY=2
      - MAX_PLAYERS=10
      - PASSWORD=servidor
      - MOTD="puto el que lo vea"
    restart: unless-stopped
