<<<<<<< HEAD
services:
  tmodloader:
    image: hexlo/terraria-tmodloader-server:latest
    container_name: tmodloader
    ports:
      - "7777:7777/tcp"
    volumes:
      - ./tmod_data:/root/.local/share/Terraria
    environment:
      - WORLD_NAME=Los homosapiens
      - WORLD_SIZE=3            # 1 = Small, 2 = Medium, 3 = Large
      - WORLD_DIFFICULTY=2      # 0 = Normal, 1 = Expert, 2 = Master, 3 = Journey
      - MAX_PLAYERS=10
      - PASSWORD=servidor
      - MOTD=puto el que lo vea
    restart: unless-stopped
=======
version: "3.8"

services:
  tmodloader:
    image: ryanfortner/tmodloader:latest
    container_name: tmodloader-server
    ports:
      - "7777:7777"
    volumes:
      - tmodloader-data:/tmodloader
    environment:
      - WORLD_NAME=Los homosapiens
      - WORLD_SIZE=3             # 1=small, 2=medium, 3=large
      - WORLD_DIFFICULTY=2       # 0=normal, 1=expert, 2=master, 3=journey
      - MAXPLAYERS=8
      - PASSWORD=servidor
      - AUTOCREATE=1
    restart: unless-stopped

volumes:
  tmodloader-data:
>>>>>>> e3324276f156d7864864abd355fad5410bff3751
